// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srtyrjtvavpfgtznhgya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydHlyanR2YXZwZmd0em5oZ3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDY4OTAsImV4cCI6MjA1MzY4Mjg5MH0.7wJ3k-C9O5LKH368Nqjd1dUxJJohBdvt83cY6CAooRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);